baseURL = 'https://mathematics.muthu.co/'
languageCode = 'en-us'
title = 'Everything Mathematics'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"
math = true
showFooter = true
footerContent = "Made with Love and Ai"

# Appearance settings
# theme = 'auto'
colorPalette = 'default'
hideHeader = false
theme = "light" 

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Software Engineer from Bangalore with a strong foundation in computer science and a passion for solving complex problems.
This site is mostly a collection of interesting topics about Mathematics
"""

# Collection to display on home
homeCollectionTitle = 'All the magic'
homeCollection = 'posts'

# Lists parameters
paginationSize = 50
listSummaries = false

# Breadcrumbs
breadcrumbs = false

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/krimuthu/"

[[params.social]]
name = "github"
url = "https://github.com/muthuspark"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "All the magic"
url = "/posts"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
# theme = "preferred_color_scheme"

enableRobotsTXT = true